spring:
  redis:
    host: 192.168.188.130
    port: 6379
    database: 0
    connect-timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
server:
  port: 8888